name: github pages

on:
  push:
    branches: [master]
  pull_request:
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Doxygen Build
      - uses: mattnotmitt/doxygen-action@v1

      - name: Deploy
      - uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
