name: github pages

on:
  push:
    branches: [master]
  pull_request:
    
jobs:
  get-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Clone Orca
        run: git clone https://github.com/cee-studio/orca
      - name: Commands
        run: mkdir docs
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: echo $(pwd)

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.3.1
        with:
          additional-packages: font-fira-code

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/html
